language: cpp
compiler:
 - gcc
 - clang
env:
  - CONFIG=minimal
  - CONFIG=full    ; SSL=openssl
  - CONFIG=full    ; SSL=gnutls
install:
  - autotest/travis/install-build-depends.sh
script:
  - autotest/travis/build-and-test.sh
