/*
 * uhub - A tiny ADC p2p connection hub
 * Copyright (C) 2007-2026, Jan Vidar Krey
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

#ifndef HAVE_UHUB_ROUTE_H
#define HAVE_UHUB_ROUTE_H

#include <stddef.h>

struct hub_info;
struct hub_user;
struct adc_message;

/**
 * Route a message by sending it to it's final destination.
 */
extern int route_message(struct hub_info* hub, struct hub_user* u, struct adc_message* msg);

/* Send-queue ceilings (exposed for unit testing). The hard limit scales with
   the connected-user count -- a slow reader accumulates messages generated by
   every other user -- but never drops below the configured floor; the soft
   limit is the fixed choke threshold. */
extern size_t get_max_send_queue(struct hub_info* hub);
extern size_t get_max_send_queue_soft(struct hub_info* hub);

/* RTF0 rich text relay (exposed for unit testing). A message carrying the RT
   flag is relayed in two variants, since clients that did not negotiate RTF0
   must not see the flag. */

/**
 * Build an RT-stripped copy of a rich text MSG.
 * @return the stripped copy, which the caller must adc_msg_free(), or NULL if
 *         the message is not a rich text MSG (or the copy could not be made).
 */
extern struct adc_message* route_rtf0_strip(struct adc_message* msg);

/**
 * Pick the message every recipient starts from: normally the original, but the
 * stripped copy when rich text is disabled hub-wide (chat_rich_text), so that
 * no client -- and no linked hub -- is handed the RT flag.
 * @param plain the RT-stripped copy, or NULL if the message is not rich text.
 */
extern struct adc_message* route_rtf0_baseline(struct hub_info* hub, struct adc_message* msg, struct adc_message* plain);

/**
 * Pick the variant of a message a given user is allowed to see.
 * @param plain the RT-stripped copy, or NULL if the message is not rich text.
 */
extern struct adc_message* route_rtf0_variant(struct hub_user* user, struct adc_message* rich, struct adc_message* plain);

/**
 * Send queued messages.
 */
extern int route_flush_pipeline(struct hub_info* hub, struct hub_user* u);

/**
 * Flush all connections that had messages queued during this event-loop
 * iteration (the deferred writes accumulated by route_to_user). Coalesces
 * each connection's queued messages into as few syscalls as possible.
 */
extern void route_flush_dirty(struct hub_info* hub);

/**
 * Remove a user from the deferred-write queue before it is destroyed, so
 * route_flush_dirty() never dereferences a freed struct.
 */
extern void route_clear_dirty(struct hub_info* hub, struct hub_user* user);

/**
 * Transmit message directly to one user.
 */
extern int route_to_user(struct hub_info* hub, struct hub_user*, struct adc_message* command);

/**
 * Broadcast message to all users.
 */
extern int route_to_all(struct hub_info* hub, struct adc_message* command);

/**
 * Broadcast message to all users subscribing to the type of message.
 */
extern int route_to_subscribers(struct hub_info* hub, struct adc_message* command);

/**
 * Broadcast initial info message to all users.
 * This will ensure the correct IP is seen by other users
 * in case nat override is in use.
 */
extern int route_info_message(struct hub_info* hub, struct hub_user* user);


#endif /* HAVE_UHUB_ROUTE_H */
